name: CSS Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Lint with StyleLinter
        run: ./node_modules/.bin/stylelint ./portfolio/src/main/webapp/css
